eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: server
server:
  port: 8085

eureka.client.fetchRegistry: true
spring.application.name: spring-cloud-eureka
